### ISSUE TITLE
Scaling fuzz effect grain for 4x resolution

### ISSUE THREAD

**Issue by SoDOOManiac** [Zodomaniac/So-Doom#12]
I have received a report that spectres are hard to see with 4x resolution, so I'd like to scale the fuzz effect pixels by 2 in case of quadres.
I know that the game scene is rendered in columns, andy idea to achieve this is to modify `R_DrawFuzzColumn` to have different initial fuzz effect position for even and odd columns.
In each frame even (including zeroth) column starts with zero `fuzzpos`, and the odd column starting `fuzzpos` is calculated based on the difference of the positions of two columns' starting pixels, so that the shades of adjacent pixels of the columns coincide.

The question is where I should put the variable signaling the odd column `boolean odd_column`, so that it toggles after rendering each fuzzed column and resets to `false` after each frame.

@fabiangreffrath, could you help me figure that out?

**Comment by fabiangreffrath** [comment]
I have code in Woof to restore lores fuzzy drawing in hires mode:

https://github.com/fabiangreffrath/woof/blob/d9ee850ed5ebf83b99344dab0e645ae4f4492e13/src/r_draw.c#L517-L592

**Comment by SoDOOManiac** [comment]
> I have code in Woof to restore lores fuzzy drawing in hires mode:

Thanks a lot!
