### ISSUE TITLE
Removal of the INTERCEPTS overflow guard but leaving the menu option to evade the limit

### ISSUE THREAD

**Issue by SoDOOManiac** [Zodomaniac/So-Doom#2]
Related commit:
https://github.com/drfrag666/chocolate-doom/commit/5d28f6cf44c70c81bc5d7227fab3e25a7a67315e
but I'd like to keep evading the limit optional, i.e. make calls to the emulation function etc. optional.
Please help me with that @drfrag666, I'm not sure how to do that correctly.
@fabiangreffrath, welcome to the discussion as well :)

**Comment by SoDOOManiac** [comment]
I hope I handled it correctly, at least switching the option makes the intercepts overflow happen or not in demo playback: https://github.com/Zodomaniac/So-Doom/commit/ed054123630b4000d5f17cf31f4451870e81b6d1

**Comment by drfrag666** [comment]
The merge is correct. As i explained i just did what @fabiangreffrath explained in the issue i linked in the forum. I reverted the guards (which were added by fabian) and removed the calls to the emulation function. The code to show how the limit increases is the same as in other cases but unfortunately not having a working console to show the messages is a serious issue in Choco.
