### ISSUE TITLE
There's only a fullscreen hud on Widescreen settings

### ISSUE THREAD

**Issue by TeamSoldierNub2** [Zodomaniac/So-Doom#3]
### Background

Version of So Doom: 5.6.1.1.

Operating System and version: Windows 10

Game: (Doom/Heretic/Hexen/Strife/other) Ultimate Doom (I and II, issue occurs on both)

Any loaded WADs and mods (please include full command line): none

### Bug description

Observed behavior: Hud is normal without widescreen, but with it, there's only full-screen. On normal, there's a hud with different screen sizes

Expected behavior: Enable Widescreen, then try pressing '-' until the numbers disappear

footage: https://streamable.com/jau7s

**Comment by SoDOOManiac** [comment]
Only no-status-bar HUD being available in widecreen mode is inherited from Crispy Doom.

Do you wish to have a HUD option like in this post https://www.doomworld.com/forum/topic/67168-crispy-doom-57-update-feb-21-2020/?do=findComment&comment=2085665 but with a status bar?

**Comment by SoDOOManiac** [comment]
I raised a question at Doomworld forums if narrow HUD with and without the status bar is ever to be implemented in Crispy. If not, I'll try to make it happen in So Doom.

**Comment by SoDOOManiac** [comment]
The 'compact HUD' would make sense without status bar only, as the latter would be obtrusive with weapon sprites (thanks to @JNechaevsky for bringing this reasoning to the discussion):
![obtrusivestatusbar](https://user-images.githubusercontent.com/15119473/75360751-51a93000-58c7-11ea-819b-a1ce4f1960dc.png)

**Comment by TeamSoldierNub2** [comment]
I was talking about how ports like The Eternity Engine and PrBoom+ as well as GZDoom handled this. An easy fix would be adding a background to each side of the HUD itself.

**Comment by TeamSoldierNub2** [comment]
The way those ports handled it is what I'm talking about. Widescreen rendering in PrBoom and Eternity Engine had smaller screen sizes too.

**Comment by TeamSoldierNub2** [comment]
> 
> 
> The 'compact HUD' would make sense without status bar only, as the latter would be obtrusive with weapon sprites (thanks to @JNechaevsky for bringing this reasoning to the discussion):
> ![obtrusivestatusbar](https://user-images.githubusercontent.com/15119473/75360751-51a93000-58c7-11ea-819b-a1ce4f1960dc.png)

You could add background sprites next to the Status Bar in Widescreen 
(pic 1: PrBoom+ widescreen w/Status Bar) ![image](https://user-images.githubusercontent.com/47698702/75484798-75c44a00-5977-11ea-85e3-f54699c4ed1e.png)
(Pic 2: Eternity Engine Widescreen w/Status Bar)
![image](https://user-images.githubusercontent.com/47698702/75485043-fbe09080-5977-11ea-9e92-d5be1e01cf38.png)

**Comment by SoDOOManiac** [comment]
Fixed by @fabiangreffrath in Crispy, will be merged to So Doom. Thanks for the suggestion!

**Comment by SoDOOManiac** [comment]
Fabian made the Compact HUD also statusbar-less only, so I am re-opening this till the time I have sufficient programming skills.

**Comment by fabiangreffrath** [comment]
I would even welcome a PR, but I am not going to work on this myself.

**Comment by SoDOOManiac** [comment]
Implemented in Crispy and merged into 5.7.5, enjoy!
