### ISSUE TITLE
Crash when trying to load a savegame from a non-loaded WAD

### ISSUE THREAD

**Issue by SoDOOManiac** [Zodomaniac/So-Doom#5]
A dialog telling which WAD the map is from with background should pop up.

**Comment by SoDOOManiac** [comment]
@fabiangreffrath, my `M_DrawCrispnessBackground` is reduced to

```
static void M_DrawCrispnessBackground(void)
{
	V_DrawPatchDirect(0, 0, &crispness_background);
	inhelpscreens = true;
}
```
Why would it cause a crash in `M_Drawer`?
```
void M_Drawer (void)
{
    static short	x;
    static short	y;
    unsigned int	i;
    unsigned int	max;
    char		string[80];
    const char          *name;
    int			start;

    inhelpscreens = false;
    
    // Horiz. & Vertically center string and print it.
    if (messageToPrint)
    {
	// [crispy] draw a background for important questions
	if (messageToPrint == 2)
	{
	    M_DrawCrispnessBackground();
	}
```

**Comment by SoDOOManiac** [comment]
UPD: crashes are also encountered in Crispy in some of my savegames. For instance, when trying to load a save from Scythe while in HoE brings the question in So Doom but crashes Crispy.
Here are the savegames.
[savegames.zip](https://github.com/Zodomaniac/So-Doom/files/4287349/savegames.zip)

**Comment by fabiangreffrath** [comment]
Do you load from the menu or from the command line?

**Comment by SoDOOManiac** [comment]
From the menu.

**Comment by fabiangreffrath** [comment]
This is because So-Doom starts its extended savegame signture with "so-doom" whereas Crispy starts its own with "crispy-doom". Crispy just cannot know that a signature starting with "so-doom" is compatible to its own and So-Doom cannot know either. Thats why they don't parse the savegames any further and just straight try to load the savegames.

https://github.com/fabiangreffrath/crispy-doom/blob/master/src/doom/p_extsaveg.c#L559

**Comment by SoDOOManiac** [comment]
What a can of worms I opened by forking Crispy XD
I think a reasonable solution would be to explicitly start the Crispy-format extended savegame signature with `crispy-doom` and merge that into So Doom, so that So Doom and other forks of Crispy if such appear adopt the extended savegame format of the parent port.

**Comment by fabiangreffrath** [comment]
> What a can of worms I opened by forking Crispy XD

:stuck_out_tongue_closed_eyes:

**Comment by SoDOOManiac** [comment]
>I think a reasonable solution would be to explicitly start the Crispy-format extended savegame signature with crispy-doom and merge that into So Doom, so that So Doom and other forks of Crispy if such appear adopt the extended savegame format of the parent port.

I only don't know where exactly the `crispy-doom` string should be put, could you please do that?

**Comment by fabiangreffrath** [comment]
That's here (with version number)
https://github.com/Zodomaniac/So-Doom/blob/master/src/doom/p_extsaveg.c#L42
and here (only "crispy-doom")
https://github.com/Zodomaniac/So-Doom/blob/master/src/doom/p_extsaveg.c#L444

**Comment by SoDOOManiac** [comment]
I think maybe I should submit a pull request to Crispy, so that forkers don't have to adjust anything to make their savegames compatible with Crispy?
