### ISSUE TITLE
Calls to V_DrawPatchDirect() need their argument casted to (patch_t *)

### ISSUE THREAD

**Issue by fabiangreffrath** [Zodomaniac/So-Doom#6]
The three calls to `V_DrawPatchDirect()` in `src/doom/m_menu.c` which have either `crispness_background` or `main_menu_background` as their third arguments should cast these very arguments to `(patch_t *)`. This is because `V_DrawPatchDirect()` strictly requires the third argument to be a pointer to a patch struct, whereas you merely pass a pointer to a constant byte array - which in turn is the representation of a patch struct, but the compiler cannot know this at this point.

This is also where your Travis CI fails, which would be a pity!

https://github.com/Zodomaniac/So-Doom/blob/807c85a8c0c5dca7a92da919ec423753300f4af1/src/doom/m_menu.c#L1281

**Comment by SoDOOManiac** [comment]
Closed in https://github.com/Zodomaniac/So-Doom/commit/8f16d463c0482b8b2b0bb236c7149f8c221c5b89, thanks a lot!
