### ISSUE TITLE
Extraspawned monsters don't count as extrakills if killed NOT with the TNTEM cheat code

### ISSUE THREAD

**Issue by SoDOOManiac** [Zodomaniac/So-Doom#7]
### Background

Version of So Doom: https://github.com/SoDOOManiac/So-Doom/commit/4f8e54e3dd2566ee6df664ef120fa0cfa7d11bbd

Operating System and version: Win 7

Game: Doom 2 v1.666

Any loaded WADs and mods: `start so-doom -iwad doom2v16.wad`, skill Ultra-Violence, then IDCLEV30

### Bug description

Observed behavior: monsters extraspawned through resurrection/nightmare/Icon of Sin don't count as `extrakills` if killed NOT with the TNTEM cheat code.

Expected behavior: monsters extraspawned through resurrection/nightmare/Icon of Sin (except Lost Souls) must count as `extrakills`.

Here the killed monster is an extraspawned one,
![DOOM0014](https://user-images.githubusercontent.com/15119473/186116662-8b956b5a-ee88-4d2e-9f29-6f8ecdf9456d.png)

but it still counts with Smart Totals enabled.
![DOOM0013_actual](https://user-images.githubusercontent.com/15119473/186116974-c1141e16-1101-4f17-a99d-82c4b6c10fdc.png)

The extraspawned monsters should be subtracted from the kill count when Smart Totals are enabled:
![DOOM0013_expected](https://user-images.githubusercontent.com/15119473/186117629-426b065a-a6ff-409d-9dc7-36ecf3a80265.png)

Also attaching the savegame to reproduce.
[doomsav3.zip](https://github.com/SoDOOManiac/So-Doom/files/9401029/doomsav3.zip)

**Comment by SoDOOManiac** [comment]
@fabiangreffrath, I find this case really fascinating! When I kill the monsters with TNTEM like you did, the extraspawns count as extrakills, but when I use weapons, they don't!

**Comment by fabiangreffrath** [comment]
You have to move this line out of the `else` condition, it currently only counts for monsters *not* killed by a player:

https://github.com/SoDOOManiac/So-Doom/blob/4f8e54e3dd2566ee6df664ef120fa0cfa7d11bbd/src/doom/p_inter.c#L741-L743

**Comment by SoDOOManiac** [comment]
Thanks a lot! I had been stuck on this for a long time.
